services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Synolia\SyliusMaintenancePlugin\:
    resource: '../../*'
    exclude: '../../{Controller,Migrations,SynoliaSyliusMaintenancePlugin.php}'

  Synolia\SyliusMaintenancePlugin\Controller\:
    resource: '../../Controller/*'
    tags: ['controller.service_arguments']

  Synolia\SyliusMaintenancePlugin\Menu\AdminMenuListener:
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

