# Delete these routes and define your own shop routes here

synolia_sylius_maintenance_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Synolia\SyliusMaintenancePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

synolia_sylius_maintenance_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Synolia\SyliusMaintenancePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
